server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/w3angb/springcloud-config.git #Github上面的git仓库名
          #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master

#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka

