server:
  port: 80

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进Eureka Server 默认为true
    fetchRegistry: true         #是否从Eureka Server抓取已有注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka

spring:
  application:
    name: cloud-provider-hystrix-order

##设置Feign客户端超时时间（OpenFeign默认支持Ribbon）
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout:  5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

